# Site settings
title: HypTrails
description: > # this means to ignore newlines until "baseurl:"
 The official resource for HypTrails. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hyptrails.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
